version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Berlin"
    labels:
      - "type:deps"
      - "type:ci"
    commit-message:
      prefix: "ci(deps)"
    open-pull-requests-limit: 5
